version: '2'

services:
  backend:
    image: 'academic-record-system:latest'
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/academic-record-system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  postgres_db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    environment:
      - POSTGRES_DB=academic-record-system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
